language: python
python: 3.7
dist: xenial
sudo: true

services:
 - mysql
 - docker

env:
  global:
    - TODO_DB_USER=root
    - TODO_DB_PASSWORD=""
    - TODO_DB_NAME=todolist
    - TODO_DB_HOST=127.0.0.1
    - PYTHONPATH=".:$PYTHONPATH"

before_install:
 - mysql -e 'CREATE DATABASE todolist CHARACTER SET utf8 COLLATE utf8_general_ci;'
 - docker build -t daisyleenr/todo-api-server:$TRAVIS_BUILD_NUMBER -t daisyleenr/todo-api-server:latest .
 - docker run -d -p 5000:5000 -e TODO_DB_USER=$TODO_DB_USER -e TODO_DB_NAME=$TODO_DB_NAME -e TODO_DB_HOST=$TODO_DB_HOST daisyleenr/todo-api-server:latest
 - docker ps -a

install:
 - pip install -r requirements.txt

script:
 - alembic upgrade head
 - pytest

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master