language: python
python: 3.7
dist: xenial
sudo: true

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE todolist;'

env:
  - TODO_DB_USER=root TODO_DB_PASSWORD="" TODO_DB_NAME=todolist TODO_DB_HOST=localhost PYTHONPATH=".:$PYTHONPATH"

# command to run tests
script:
  - export PYTHONPATH=.:$PYTHONPATH
  - alembic upgrade head
  - pytest

