version: "3.3"

services:
  todo-api-server:
    image: daisyleenr/todo-api-server:latest
    ports:
      - "5001:5000"
    restart: always
    environment:
      TODO_DB_USER: todolist
      TODO_DB_PASSWORD: todolist
      TODO_DB_NAME: todolist
      TODO_DB_HOST: db
      PYTHONPATH: .:$PYTHONPATH
    command: bash -c "alembic upgrade head && gunicorn --bind 0.0.0.0:5000 app:app"
  todo-frontend:
    image: daisyleenr/todo-frontend:latest
    ports:
      - "3001:3000"
    restart: always
volumes:
  db_data:
