"""add checked column

Revision ID: c9c7446eb04d
Revises: 4d26e8dc4f92
Create Date: 2019-02-26 19:58:01.716231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c7446eb04d'
down_revision = '4d26e8dc4f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'checked')
    # ### end Alembic commands ###
